services:
  app:  
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_QR_ENCRYPTION_SECRET: ${NEXT_PUBLIC_QR_ENCRYPTION_SECRET}
    ports:
      - "3000:3000"
      - "6969:6969"
    environment:
      - DB_URL=${DB_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - REMOTE_PATTERNS=${REMOTE_PATTERNS}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_QR_ENCRYPTION_SECRET=${NEXT_PUBLIC_QR_ENCRYPTION_SECRET}
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pap-reg-system:/var/lib/postgresql/data

volumes:
  pap-reg-system: